set foreign_key_checks=0;
INSERT INTO fareperkm (type, class, fare_per_km) VALUES
('Express', 'SL', 0.70),          
('Express', '2A', 1.00),          
('Express', '3A', 1.30),          
('Express', 'CC', 1.80),         
('Express', '2S', 0.70),         
('Superfast', 'SL', 0.80),       
('Superfast', '2A', 1.50),        
('Superfast', '3A', 1.50),       
('Superfast', 'CC', 1.40),        
('Superfast', '2S', 0.80),        
('Superfast', '3E', 2.00),       
('Superfast', '1A', 2.50),
('Rajdhani', '1A', 2.50),       
('Rajdhani', '2A', 2.00),     
('Rajdhani', '3A', 1.50),        
('Rajdhani', 'SL', 1.00),
('Rajdhani', 'EC', 0.95),
('Tejas', 'EC', 2.50),         
('Tejas', 'CC', 1.50),
('Vande Bharat', 'EC', 3.00),     
('Vande Bharat', 'CC', 1.80),
('Duronto', '1A', 3.00),              
('Duronto', 'SL', 0.70),              
('Duronto', '2A', 2.50),              
('Duronto', '3A', 1.50),       
('Duronto', 'CC', 1.20),
('Shatabdi', '1A', 3.50),
('Shatabdi', '2A', 2.80),             
('Shatabdi', 'EC', 2.50),              
('Shatabdi', 'EA', 3.00),
('Gatimaan', 'EC', 3.50),              
('Gatimaan', 'CC', 1.75);
set foreign_key_checks=1;