set foreign_key_checks=0;
INSERT INTO station (id, division_id, name)
VALUES 
('ADI', 'ADI', 'Ahmedabad Jn'),
('ND', 'BRC', 'Nadiad Jn'),
('BH', 'BRC', 'Bharuch Jn'),
('ST', 'BCT', 'Surat'),
('VAPI', 'BCT', 'Vapi'),
('BVI', 'BCT', 'Borivali'),
('MMCT', 'BCT', 'Mumbai Central'),
('CSMT', 'CSTM', 'C Shivaji Maharaj T'),
('KYN', 'CSTM', 'Kalyan Jn'),
('BSL', 'CSTM', 'Bhusaval Jn'),
('ET', 'BPL', 'Itarsi Jn'),
('JBP', 'JBP', 'Jabalpur'),
('STA', 'JBP', 'Satna'),
('PCOI', 'PRYJ', 'Prayagrajcheoki'),
('DDU', 'DDU', 'Dd Upadhyaya Jn'),
('RPR', 'DNR', 'Raghunathpur'),
('PNBE', 'DNR', 'Patna Jn'),
('JP', 'JP', 'Jaipur'),
('KSG', 'JP', 'Kishangarh'),
('AII', 'AII', 'Ajmer Jn'),
('BHL', 'AII', 'Bhilwara'),
('COR', 'RTM', 'Chittaurgarh'),
('NMH', 'RTM', 'Nimach'),
('MDS', 'RTM', 'Mandsor'),
('RTM', 'RTM', 'Ratlam Jn'),
('BRC', 'BRC', 'Vadodara Jn (RL)'),
('BSR', 'BCT', 'Vasai Road'),
('PUNE', 'PUNE', 'Pune Jn (RL)'),
('SUR', 'SUR', 'Solapur Jn'),
('KLBG', 'SUR', 'Kalaburagi'),
('YG', 'GTL', 'Yadgir'),
('RC', 'GTL', 'Raichur'),
('MALM', 'GTL', 'Manthralayam Road'),
('GTL', 'GTL', 'Guntakal Jn (Rev)'),
('BAY', 'UBL', 'Bellary Jn'),
('CTA', 'MYS', 'Chitradurg'),
('JR', 'MYS', 'Chikjajur Jn'),
('RRB', 'MYS', 'Birur Jn'),
('ASK', 'MYS', 'Arsikere Jn'),
('TK', 'SBC', 'Tumkur'),
('YPR', 'SBC', 'Yasvantpur Jn'),
('LJN', 'LJN', 'Lucknow Ne'),
('CNB', 'PRYJ', 'Kanpur Central'),
('TDL', 'PRYJ', 'Tundla Jn'),
('GZB', 'DLI', 'Ghaziabad'),
('NDLS', 'DLI', 'New Delhi');
set foreign_key_checks=1;
